[platformio]
src_dir = main
default_envs = teensy41

[env:teensy41]
platform = teensy
board = teensy41
framework = arduino
monitor_speed = 9600
lib_deps =
    adafruit/Adafruit GFX Library
    adafruit/Adafruit SSD1306